// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxPo2_Inl_1bvMTUIngnHtzF4aDdW_ZI',
    appId: '1:618863725756:android:6d41735b5600fdd5a054b9',
    messagingSenderId: '618863725756',
    projectId: 'budgetin-f877d',
    storageBucket: 'budgetin-f877d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIZTGOH0lrBbhUGus-DXtTfP2v5m4s2A',
    appId: '1:618863725756:ios:9b3a8d1b5f2cfe81a054b9',
    messagingSenderId: '618863725756',
    projectId: 'budgetin-f877d',
    storageBucket: 'budgetin-f877d.firebasestorage.app',
    androidClientId: '618863725756-lbjpjn70stm7nbj21cq49a9aimof16ad.apps.googleusercontent.com',
    iosClientId: '618863725756-htc5pu5sql8ut55aed32rd52is3q9gmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.buudgetinApp',
  );
}
